#!/usr/bin/env sh
# Copyright 2020 The Maritime Whale Authors. All rights reserved.
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE.txt file.
#
# Simple script to install necessary project dependencies.

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo yum install python3
    sudo easy_install pip
    sudo pip3 install pip-upgrader # https://github.com/simion/pip-upgrader
    pip-upgrade --skip-virtualenv-check -p all
elif [[ "$OSTYPE" == "darwin"* ]]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    brew install jq
    brew install python
    sudo easy_install pip
    pip3 install pip-upgrader
    pip-upgrade --skip-virtualenv-check -p all
elif [[ "$OSTYPE" == "cygwin" ]]; then
    echo "(cygwin) OS not supported"
elif [[ "$OSTYPE" == "msys" ]]; then
    echo "(msys) OS not supported"
elif [[ "$OSTYPE" == "win32" ]]; then
    echo "(win32) OS not supported"
elif [[ "$OSTYPE" == "freebsd"* ]]; then
    echo "(freebsd) OS not supported"
else
    echo "(unknown) OS not supported"
fi
