#!/bin/sh

debug_mode=0
for arg in "$@"; do
    if [ "$arg" == "debug" ]; then
        echo "Running in debug mode..."
        debug_mode=1
    else
        echo "./run: illegal option -- $arg"
        echo "Usage: ./run [debug]"
        exit 1
    fi
done
LOGS=logs
if [ ! -d "$LOGS" ]; then
    mkdir $LOGS
fi
rm logs/sync_*.log > /dev/null 2>&1
rm logs/vmr_*.log > /dev/null 2>&1
rm logs/wind_*.log > /dev/null 2>&1
rm logs/depend_*.log > /dev/null 2>&1
rm logs/report_*.log > /dev/null 2>&1
if [ $debug_mode == 0 ]; then
    pip-upgrade --skip-virtualenv-check -p all 2>> logs/depend_err.log 1>> logs/depend_out.log
else
    pip-upgrade --skip-virtualenv-check -p all
fi
if [ $debug_mode == 0 ]; then
    find logs/* -mtime +1 -exec rm {} \; > /dev/null 2>&1
    rm -rf temp/* > /dev/null 2>&1
fi
CONFIG=conf
RICONF=conf/riwhale.config
if [ ! -d "$CONFIG" ]; then
    mkdir $CONFIG
    echo "Config directory not found. Creating directory: ./$CONFIG ."
    exit 1
else
    if [ ! -f "$RICONF" ]; then
        echo "Missing config file. ./$RICONF does not exist."
        exit 1
    fi
fi
REPO=html/riwhale.github.io/
OAUTH_TOKEN="$( jq -r ".oauth" "$RICONF" )"
if [ ! -d "$REPO" ]; then
    HTML=html
    if [ ! -d "$HTML" ]; then
        mkdir $HTML
    fi
    cd html
    git clone https://$OAUTH_TOKEN:x-oauth-basic@github.com/riwhale/riwhale.github.io.git 2>> ../logs/sync_err.log 1>> ../logs/sync_out.log
    cd ..
fi
SRCDIR=src
if [ ! -d "$SRCDIR" ]; then
    echo "No src directory found."
    echo "Please follow the installation instructions at https://github.com/davnajork/maritime-whale-map and try again."
    exit 1
fi
TEMP=temp
if [ ! -d "$TEMP" ]; then
    mkdir $TEMP
fi

# LINKS
# https://www.ndbc.noaa.gov/docs/ndbc_web_data_guide.pdf
# https://www.ndbc.noaa.gov/data/realtime2/
# https://www.ndbc.noaa.gov/wstat.shtml

# USEFUL SENSOR INFO (DO NOT DELETE):
# 41004 ch off 32.501 /  -79.099
# 41008 sv off 31.400 / -80.866
# FBIS1 ch near 32.803 /  -79.624
# 41033 sv near 32.279 / -80.406
BUOYS="41004 41033"
for BUOY in $BUOYS; do
    curl https://www.ndbc.noaa.gov/data/realtime2/$BUOY.txt -o "$TEMP/$BUOY.txt" 2>> logs/wind_err.log 1>> logs/wind_out.log
done
ADV_BUOYS="41008 FBIS1"
for BUOY in $ADV_BUOYS; do
  curl https://www.ndbc.noaa.gov/data/realtime2/$BUOY.cwind -o "$TEMP/$BUOY.txt" 2>> logs/wind_err.log 1>> logs/wind_out.log
done
cd html/riwhale.github.io
git pull https://$OAUTH_TOKEN:x-oauth-basic@github.com/riwhale/riwhale.github.io.git 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
CACHE=../../cache
if [ ! -d "$CACHE" ]; then
    mkdir $CACHE
fi
yes | cp -rf blacklist.txt ../../cache/blacklist.txt
cd ../../cache
SECURE_CACHE=secure-cache/
if [ ! -d "$SECURE_CACHE" ]; then
    git clone https://$OAUTH_TOKEN:x-oauth-basic@github.com/riwhale/secure-cache.git 2>> ../logs/sync_err.log 1>> ../logs/sync_out.log
fi
cd secure-cache
git pull https://$OAUTH_TOKEN:x-oauth-basic@github.com/riwhale/secure-cache.git 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
cd ..
cp -rf secure-cache/[0-9]* . > /dev/null 2>&1
cd ../src
MAIN_RET_VAL=1
if [ $debug_mode == 0 ]; then
    python3 main.py 2>> ../logs/vmr_err.log 1>> ../logs/vmr_out.log
    MAIN_RET_VAL=$?
else
    python3 main.py
fi
cd ../html/riwhale.github.io
if [ $debug_mode == 0 ]; then
    PLOT=../level_one.html
    if [ ! -f "$PLOT" ]; then
        echo "Cache up to date. No new plots generated." 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
    else
        echo "Initiating upload..." 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        rm -rf level_one.html level_two_*.html seasonal_table.html vspd_hist_*.html wspd_hist_*.html wspd_vs_vspd_*.html vspd_strip_*.html line_*.html channel_occupation_*.html master-*.* blacklist.txt dashboard.csv 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        git commit -am "wipe plots, master XLSXs/CSVs, blacklist, and dashboard" 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        mv ../../cache/master-*.* . 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        mv ../../cache/blacklist.txt . 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        mv ../dashboard.csv . 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        mv ../*.html . 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        git add level_one.html level_two_*.html seasonal_table.html vspd_hist_*.html wspd_hist_*.html wspd_vs_vspd_*.html vspd_strip_*.html line_*.html channel_occupation_*.html master-*.* blacklist.txt dashboard.csv 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        git commit -am "upload plots, master XLSXs/CSVs, blacklist, and dashboard" 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        git push https://$OAUTH_TOKEN:x-oauth-basic@github.com/riwhale/riwhale.github.io.git 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        cd ../../cache
        cp -rnf [0-9]* secure-cache
        cd secure-cache
        git add -A 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        git commit -am "update cache file(s)" 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        git push https://$OAUTH_TOKEN:x-oauth-basic@github.com/riwhale/secure-cache.git 2>> ../../logs/sync_err.log 1>> ../../logs/sync_out.log
        cd ../../src
        if [ $MAIN_RET_VAL == 0 ]; then
            python3 error_reporting.py 2>> ../logs/report_err.log 1>> ../logs/report_out.log
        else
            echo "FATAL ERROR -- SILENT (NON-COMM) CASE" 2>> ../logs/report_err.log 1>> ../logs/report_out.log
            python3 error_reporting.py 2>> ../logs/report_err.log 1>> ../logs/report_out.log
        fi
        cd ../html/riwhale.github.io
    fi
fi

cd ../..
exit 0
